Repository UBC-MDS/pictureperrrfect, pull requests merged in 2021-03, with the labels that each got.

#6 Add roxygen2 documentation for rotation function
  R/rotation_perrrfect.R
Labels: documentation

#8 Update comments for get_property_perrrfect()
  R/get_property_perrrfect.R
Labels: documentation

#10 Readme update
  .github/CONTRIBUTING.md
  DESCRIPTION
  README.Rmd
  README.md
Labels: documentation

#19 feat: Feature filter_perrrfect
  R/filter_perrrfect.R
  img/input_beautiful_Vancouver.jpg
  img/output_beautiful_Vancouver_blur_21.jpg
  img/output_beautiful_Vancouver_sharpen_21.jpg
  tests/testthat.R
  tests/testthat/test-filter_perrrfect.R
Labels: code

#20 feat: Feature rotation_perrrfect
  R/rotation_perrrfect.R
  tests/testthat.R
  tests/testthat/test-rotation_perrrfect.R
Labels: code, enhancement

#21 Implemented get property feature and passed all tests
  R/get_property_perrrfect.R
  img/black.png
  img/blue.png
  img/green.png
  img/red.png
  img/white.png
  tests/testthat/test-get_property_perrrfect.R
Labels: code

#23 Add tolerance to tests
  tests/testthat/test-filter_perrrfect.R
Labels: bug

#32 Vignette m4
  vignettes/.gitignore
  vignettes/picture_perrrfect.Rmd
Labels: documentation
